---
title: "Liang Fu"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Education

-   Ph.D. Economics, [University at Albany, SUNY](https://www.albany.edu/), U.S., 2022

-   M.A. Economics, [Central University of Finance and Economics](http://en.cufe.edu.cn/), China, 2014

-   B.S. Management, [Qingdao University](https://istudy.qdu.edu.cn/en/index), China, 2011



# Research Fields

-   Monetary Economics
-   International Economics



# Publications

-   Fu, Liang and Chun-Yu Ho, Monetary Policy Surprises and Interest Rates under China's Evolving Monetary Policy Framework. *Emerging Markets Review*



<!-- # Teaching Experience -->

<!-- -   University at Albany, SNUY, 08/2018 - 12/2021 -->

<!--     -   Economic Statistics (Undergraduate): Fall 2021 -->
<!--     -   Money and Banking (Undergraduate): Summer 2018, Fall 2018, Fall 2019, Spring 2020 -->
<!--     -   Intermediate Macroeconomics (Undergraduate): Spring 2019, Fall 2020, Spring 2021 -->



# Research Experience

-   Research Assistant, [New York State Division of the Budget](https://www.budget.ny.gov/), U.S., 05/2016 - 08/2018



# Scholarships, Honors, and Awards

-   *Helen Horowitz Excellence in Teaching Award*, University at Albany, SUNY, 2019



# Conference and Seminar Presentations

-   Central University of Finance and Economics (China Academy of Finance and Development)




# Skills

-   *Computer*: R, Stata, MATLAB, SAS, LaTeX

-   *Language*: Chinese Mandarin (Native), English (Fluent)



